"""order address

Revision ID: 22a74cd7077d
Revises: 6e0067aacf9e
Create Date: 2025-12-13 19:39:08.773185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a74cd7077d'
down_revision: Union[str, Sequence[str], None] = '6e0067aacf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_cost', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_column('orders', 'shipping_cost')
    # ### end Alembic commands ###
