"""Add user profile fields

Revision ID: 595d5db59174
Revises: 87e456d1c8fd
Create Date: 2025-12-07 10:19:43.245856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595d5db59174'
down_revision: Union[str, Sequence[str], None] = '87e456d1c8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('instagram_handle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instagram_handle')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
