"""sincronizando_schema_com_models

Revision ID: 98577da1a7f8
Revises: e5791fb4c87c
Create Date: 2025-11-23 11:05:34.017713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98577da1a7f8'
down_revision: Union[str, Sequence[str], None] = 'e5791fb4c87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
