"""add sup ref

Revision ID: 9cb5c9a8f18e
Revises: e4393c6ba548
Create Date: 2025-12-09 15:21:49.969213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb5c9a8f18e'
down_revision: Union[str, Sequence[str], None] = 'e4393c6ba548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_ref', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'supplier_ref')
    # ### end Alembic commands ###
