"""Implement Sales Case and detailed inventory models

Revision ID: a27048dbe44e
Revises: 
Create Date: 2025-11-11 15:47:15.982000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27048dbe44e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_column('orders', 'created_at')
    op.add_column('products', sa.Column('on_loan_quantity', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('sales_case_items', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_case_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_cases', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ON_LOAN', 'RETURNED', 'OVERDUE', name='salescasestatus'),
               nullable=False,
               postgresql_using='status::salescasestatus')
    op.add_column('users', sa.Column('role', sa.Enum('CUSTOMER', 'SALES_REP', 'ADMIN', name='userrole'), nullable=False,server_default='CUSTOMER'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'role')
    op.alter_column('sales_cases', 'status',
               existing_type=sa.Enum('ON_LOAN', 'RETURNED', 'OVERDUE', name='salescasestatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales_case_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_case_items', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('products', 'on_loan_quantity')
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    # ### end Alembic commands ###
