"""frete

Revision ID: c17d1ec249ce
Revises: ca69e41580a8
Create Date: 2025-12-01 22:38:49.339061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17d1ec249ce'
down_revision: Union[str, Sequence[str], None] = 'ca69e41580a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.add_column('products', sa.Column('weight', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('width', sa.Integer(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('height', sa.Integer(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('depth', sa.Integer(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'depth')
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'weight')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
