"""add cod_cat to products

Revision ID: cd6531ead7e0
Revises: f140eae061eb
Create Date: 2025-12-09 20:53:00.842553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6531ead7e0'
down_revision: Union[str, Sequence[str], None] = 'f140eae061eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cod_cat', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_products_cod_cat'), 'products', ['cod_cat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_cod_cat'), table_name='products')
    op.drop_column('products', 'cod_cat')
    # ### end Alembic commands ###
