"""Refatoracao do modelo de precos com cost_price, selling_price

Revision ID: e5791fb4c87c
Revises: b29c7dfcd4be
Create Date: 2025-11-19 22:32:17.899110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5791fb4c87c'
down_revision: Union[str, Sequence[str], None] = 'b29c7dfcd4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
